### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by cristianocca** [iLexDev/ASP.NET-WebApi-MultipartDataMediaFormatter#13]
Hi there, is this still active? Just wondering if an external library like this is still needed for Web Api 2, since I couldn't find anything similar.

**Comment by iLexDev** [comment]
Hello! Yes, it is steel useful for Web Api 2. As far as I remember such
custom solutions is obsolete only for new asp.net core.

2016-10-06 0:53 GMT+03:00 Cristiano Coelho <notifications@github.com>:

**Comment by cristianocca** [comment]
Hi, I have tried it and it works like a charm, I can't believe something like this isn't supported natively. I'm wondering if you are still maintaining this. 

I would like to know and/or even do it myself as a pull request, if it is possible to change the actual data type used to store the file contents ( right now a byte[]) to something like a spooled file that will either save to a memory stream or a disk temporary file if it gets too large, since a byte[] seems like it could blow up in any time with large files.

**Comment by iLexDev** [comment]
Hi, thank you for the suggestion.

From the beginning this formatter was not designed to handle uploading
really large files and I didn't investigate all issues related to this
topic in asp.net web api.

The easiest solution would be to add another file model type with stream
inside instead of byte[]. Maybe this stream should be a reference to
HttpStream from HttpContent, I am not fully sure about this.

It should be well investigated and covered by tests and I am not sure if I
find enough time to do this in a nearest future.

2016-10-07 6:03 GMT+03:00 Cristiano Coelho <notifications@github.com>:
